<?php
/**
 * Created by PhpStorm.
 * User: dzozulya
 * Date: 03.10.16
 * Time: 14:25
 */

namespace app\behaviors;



use app\models\User;
use yii\base\Behavior;
use yii\base\Exception;
use yii\behaviors\AttributeBehavior;
use yii\db\ActiveRecord;

class IpBehavior extends  Behavior
{
    public $ipAttribute = 'user_ip';

    private $ip;

    public function events()
    {
        return [
            ActiveRecord::EVENT_BEFORE_INSERT => 'getIpData',
            ActiveRecord::EVENT_BEFORE_UPDATE => 'getIpData',
            User::EVENT_AFTER_LOGIN => 'afterLogin',

        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->ip = \Yii::$app->request->getUserIP();

    }

    public function getIpData()
    {
        if($this->ip) {
            $this->owner->{$this->ipAttribute} = $this->ip;

        } else {
            throw new Exception('No Ip data to Insert');
        }
    }
    public function afterLogin($event)
    {
        $user = $event->identity;
        $user->touch($this->ipAttribute);
        $user->save(false);
    }
}




